{% set name = "anaconda-clean" %}
{% set version = "1.1.0" %}
{% set build_number = "2" %}
{% set checksum = "595adf8cb14535c229ca90abf9606b37e14434bcc7d34b6097f44730a23b201b" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/AnacondaRecipes/anaconda-clean-feedstock/archive/refs/tags/{{ version }}.zip
  sha256: {{ checksum }}

build:
  number: {{ build_number }}
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv "
  entry_points:
    - anaconda-clean = anaconda_clean:main

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  commands:
    - anaconda-clean --help
  imports:
    - anaconda_clean

about:
  home: https://github.com/ContinuumIO/anaconda-clean
  license: BSD
  summary: Delete Anaconda configuration files
  description: |
    anaconda-clean removes configuration files and directories from Anaconda and its programs.
  doc_url: https://github.com/ContinuumIO/anaconda-clean
  doc_source_url: https://github.com/ContinuumIO/anaconda-clean/blob/master/README.md
  dev_url: https://github.com/ContinuumIO/anaconda-clean

extra:
  recipe-maintainers:
    - jjhelmus
