package:
  name: anaconda_clean
  version: "0.9"

source:
  git_rev: v0.9
  git_url: https://github.com/r-jain1/anaconda_clean.git

build:
  entry_points:
    - clean = anaconda_clean:main

requirements:
  build:
    - python
    - future

  run:
    - python
    - future

test:
  imports:
    - anaconda_clean

about:
  home: http://pyhacker.com/pages/sas7bdat.html
  license: MIT
  summary: Delete Anaconda configuration files 
  dev_url: https://github.com/r-jain1/anaconda_clean
