package:
  name: anaconda-clean
  version: "1.0"

source:
  git_rev: v1.0
  git_url: https://github.com/ContinuumIO/anaconda-clean

build:
  entry_points:
    - clean = anaconda_clean:main

requirements:
  build:
    - python

  run:
    - python

test:
  imports:
    - anaconda_clean

about:
  home: https://github.com/ContinuumIO/anaconda-clean
  license: MIT
  summary: Delete Anaconda configuration files
  dev_url: https://github.com/ContinuumIO/anaconda-clean
